### ISSUE TITLE
Configure github actions to use docker compose to be able to run functional tests

### ISSUE THREAD

**Issue by Tyagi-Gaurav** [Tyagi-Gaurav/Movie#14]
- [x] Can we run this as part of PR check

**Comment by Tyagi-Gaurav** [comment]
There's a problem where some of the validation tests are failing due to 500 where a 400 validation error is expected. These validation features are in `/Movie/functionalTest/src/test/resources/features/login/validation.feature`.

The error thrown from container running on github actions is 
```
2021-06-28 16:06:27 84793b25-5bca-4ae5-b5a4-34e3a106aca3 ERROR SystemExceptionHandler:382 - JSON parse error: Cannot construct instance of `com.gt.scr.movie.resource.domain.ImmutableAccountCreateRequestDTO$Builder`, problem: UserName length should be between 4 and 20.; nested exception is com.fasterxml.jackson.databind.exc.ValueInstantiationException: Cannot construct instance of `com.gt.scr.movie.resource.domain.ImmutableAccountCreateRequestDTO$Builder`, problem: UserName length should be between 4 and 20.
 at [Source: (PushbackInputStream); line: 1, column: 92]
org.springframework.http.converter.HttpMessageNotReadableException: JSON parse error: Cannot construct instance of `com.gt.scr.movie.resource.domain.ImmutableAccountCreateRequestDTO$Builder`, problem: UserName length should be between 4 and 20.; nested exception is com.fasterxml.jackson.databind.exc.ValueInstantiationException: Cannot construct instance of `com.gt.scr.movie.resource.domain.ImmutableAccountCreateRequestDTO$Builder`, problem: UserName length should be between 4 and 20.
 at [Source: (PushbackInputStream); line: 1, column: 92]
	at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.readJavaType(AbstractJackson2HttpMessageConverter.java:389)
	at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.read(AbstractJackson2HttpMessageConverter.java:342)
	at org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodArgumentResolver.readWithMessageConverters(AbstractMessageConverterMethodArgumentResolver.java:185)
	at org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor.readWithMessageConverters(RequestResponseBodyMethodProcessor.java:158)
	at org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor.resolveArgument(RequestResponseBodyMethodProcessor.java:131)
	at org.springframework.web.method.support.HandlerMethodArgumentResolverComposite.resolveArgument(HandlerMethodArgumentResolverComposite.java:121)
	at org.springframework.web.method.support.InvocableHandlerMethod.getMethodArgumentValues(InvocableHandlerMethod.java:170)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:894)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
```
